apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-depl
  template:
    metadata:
      labels:
        app: server-depl
    spec:
      containers:
        - name: server-depl
          image: keysoutsourcedocker/node-web-app:latest
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: basics
            - name: NATS_CLIENT_ID
              value: clientIdMyFoot
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server-depl
  type: ClusterIP
  ports:
    - name: server-srv
      protocol: TCP
      port: 3000
      targetPort: 3000