name: basics-frontend
on:
  pull_request:
    paths:
      - "basics-frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd basics-frontend && npm install && npm run test:ci
